version: "3.10.2"
   
services:
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./data/db:/root/db
    environment:
      - SQLITE3_DB=db.sqlite3
  web:
    build: .
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000 
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db