# Generated by Django 4.0.2 on 2022-03-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=300)),
                ('amount_of_upvotes', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author_name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'News ',
                'verbose_name_plural': 'News ',
                'ordering': ['-created_at'],
            },
        ),
    ]
