# Generated by Django 4.0.2 on 2022-03-28 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='comeents',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='news.comments'),
        ),
    ]
