# Generated by Django 4.0.2 on 2022-03-28 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_comeents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='comeents',
            new_name='comments',
        ),
    ]
